export MONGODB_HOST=localhost
export MONGODB_PORT=27017
export MONGODB_USR_NAME=NONE 
export MONGODB_PASSWORD=NONE
export MONGODB_DBNAME=uptime_db

export MQTT_BROKER_HOST=127.0.0.1
export MQTT_BROKER_PORT=1883
export MQTT_BROKER_USR_NAME=NONE
export MQTT_BROKER_PASSWORD=NONE

export INFLUXDB_HOST=localhost
export INFLUXDB_PORT=8086
export INFLUXDB_USR_NAME=NONE
export INFLUXDB_PASSWORD=NONE
export INFLUXDB_DBNAME=sensors


echo MONGODB_HOST: $MONGODB_HOST
echo MONGODB_PORT: $MONGODB_PORT
echo MONGODB_USR_NAME: $MONGODB_USR_NAME
echo MONGODB_PASSWORD: $MONGODB_PASSWORD
echo MONGODB_DBNAME: $MONGODB_DBNAME

echo MQTT_BROKER_HOST: $MQTT_BROKER_HOST
echo MQTT_BROKER_PORT: $MQTT_BROKER_PORT
echo MQTT_BROKER_USR_NAME: $MQTT_BROKER_USR_NAME
echo MQTT_BROKER_PASSWORD: $MQTT_BROKER_PASSWORD

echo INFLUXDB_HOST: $INFLUXDB_HOST
echo INFLUXDB_PORT: $INFLUXDB_PORT
echo INFLUXDB_USR_NAME: $INFLUXDB_USR_NAME
echo INFLUXDB_PASSWORD: $INFLUXDB_PASSWORD
echo INFLUXDB_DBNAME: $INFLUXDB_DBNAME
